### ISSUE TITLE
ICD codes

### ISSUE THREAD

**Issue by briatte** [klpn/mortchartgen#1]
Hi,

`chartgen.py` uses the following values to match ICD codes with the appropriate nomenclature: `07A`, `08A`, `09B`, `101`, and `10` (lines 125-153).

However, the current WHO mortality files have more values than that:

```
07A     07B     08A     08B     09A     09B     09C     09N     101     103     104     10M     UE1
```

What am I missing here?

**Comment by klpn** [comment]
The reason for this omission is that I have used the script to generate charts for populations/years with relatively good data quality, which use only the assigned lists (`10` is, as seen by the regex on line 156, used for the lists "103", "10M" and "104", because I currently don't have any cause definitions using the 4th character, which is only included in "104" and "10M"). The other lists that are not included are lists which are used by special populations (e.g. "09C" for parts of China) or condensed lists with a lower degree of precision, where it would be impossible to adequately define some of the causes I use. 

I discuss the choice of populations and cause definitions more in the [site documentation](https://github.com/klpn/mortchartgen/blob/master/docs/mortchartdoc.md) (but it is currently only in Swedish).

**Comment by briatte** [comment]
That makes sense, thank you!

Context: I'm trying to replicate the complete thing, but am running into issues with pandas-0.16.2. The question popped up while I was looking at the code.
